# Then target that deployment file:
#
#     $ bosh deployment path/to/file/above
#
# Then apply this template:
#
#     $ bosh diff templates/aws/single_vm.yml.erb
#
---
name: NAME
director_uuid: UUID
networks: {}
properties:
  redis:
    resource: medium
    
